export {default as Layout} from './Layout/Layout'
export {default as Home} from './Home/Home'
export {default as Catalog} from './Catalog/Catalog'
export {default as Cart} from './Cart/Cart'
// export {default as Cart} from './Cart/Cart'